[BREAKING] Remove "/proxy" endpoint
SAP/ui5-server pull request #550
Opened 2022-11-30 15:51 UTC by RandomByte

BREAKING CHANGE:
This removes the "/proxy" endpoint and the corresponding
"connectUi5Proxy" middleware from the standard ui5-server.
Internally, this middleware made use of the connect-openui5 proxy
implementation (https://github.com/SAP/connect-openui5#proxy).

More sophisticated proxy solutions for ui5-server are already available
in the form of custom middleware extensions from the UI5-community.

The UI5 Team might provide a dedicated custom middleware extension,
with similar functionality, in the future.

2022-12-19 10:24 UTC, matz3 commented on lib/middleware/MiddlewareManager.js
> +				refMiddlewareIdx = this.middlewareExecutionOrder.length; // push
Shouldn't we use before `nonReadRequests` then? Or just fail with an error like for the removed tasks.

2022-12-20 09:43 UTC, d3xter666 commented on lib/middleware/MiddlewareManager.js
> +				refMiddlewareIdx = this.middlewareExecutionOrder.length; // push
I had some toughts in the same direction, but then I was thinking it'd be more convenient to fail gracefully.

On the other side attaching to a certain task, either before or after, might expect some specific order of the middleware, thus resulting also in unexpected output.

Tasks were implemented to throw an error in such a case, so this might be the key here: https://github.com/SAP/ui5-project/blob/main/lib/build/TaskRunner.js#L341-L347

2022-12-21 10:55 UTC, d3xter666 commented on lib/middleware/MiddlewareManager.js
> +				refMiddlewareIdx = this.middlewareExecutionOrder.length; // push
We've agreed to fail in such a case with a meaningful message before that.
The reasoning is that if we fail gracefully some apps might not migrate their references at all.

2022-12-21 11:13 UTC, flovogt commented on lib/middleware/MiddlewareManager.js
> +				log.warn(
if we fail, why we need the warning?

2022-12-21 11:57 UTC, flovogt requested changes

2022-12-21 11:57 UTC, flovogt commented on test/lib/server/middleware/MiddlewareManager.js
> +	esmock.purge(StubbedMiddlewareManager);
purge is not needed here because a simple "esmock" is used. Only when using "esmock.p" a manual purge is needed

2022-12-21 12:50 UTC, flovogt approved these changes

2022-12-21 12:54 UTC, merged