[FEATURE] manifest.json: Auto-fill supportedLocales
SAP/ui5-server pull request #617
Opened 2023-11-20 15:32 UTC by flovogt

JIRA: CPOUI5FOUNDATION-296

2024-01-23 08:37 UTC, d3xter666 approved these changes

2024-01-24 11:42 UTC, d3xter666 commented on test/lib/server/middleware/serveResources.js
> +	t.is(content, expected);
```suggestion
	t.deepEqual(content, expected);
```

2024-01-24 11:44 UTC, d3xter666 commented on test/lib/server/middleware/serveResources.js
> +		await esmock.p("../../../../lib/middleware/serveResources", {
When using `esmock.p`, after the job is done, it should be `esmock.purge(t.context.serveResourcesMiddlewareWithMock)`

2024-01-24 11:45 UTC, d3xter666 commented on test/lib/server/middleware/serveResources.js
> +	t.is(content, expected);
```suggestion
	t.deepEqual(content, expected);
```

2024-01-24 11:46 UTC, d3xter666 commented on test/lib/server/middleware/serveResources.js
> +	t.is(content, expected);
```suggestion
	t.deepEqual(content, expected);
```

2024-01-24 11:46 UTC, d3xter666 commented on test/lib/server/middleware/serveResources.js
> +	t.is(content, expected);
```suggestion
	t.deepEqual(content, expected);
```

2024-01-25 14:02 UTC, flovogt commented on test/lib/server/middleware/serveResources.js
> +	t.is(content, expected);
Its a string comparison, so "===" check should be fine, isn't?

2024-01-25 14:02 UTC, flovogt commented on test/lib/server/middleware/serveResources.js
> +	t.is(content, expected);
Its a string comparison, so "===" check should be fine, isn't?

2024-01-25 14:02 UTC, flovogt commented on test/lib/server/middleware/serveResources.js
> +	t.is(content, expected);
Its a string comparison, so "===" check should be fine, isn't?

2024-01-25 14:02 UTC, flovogt commented on test/lib/server/middleware/serveResources.js
> +	t.is(content, expected);
Its a string comparison, so "===" check should be fine, isn't?

2024-01-25 20:35 UTC, RandomByte commented on test/lib/server/middleware/serveResources.js
> +	t.is(content, expected);
From my understanding, deepEqual typically only useful when comparing structured types.

However, according to the documentation it might do some additional formatting for multiline strings, which might make it usefully here?

https://github.com/concordancejs/concordance?tab=readme-ov-file#formatting-details

Might be worth testing!

2024-01-26 10:57 UTC, d3xter666 commented on test/lib/server/middleware/serveResources.js
> +		await esmock.p("../../../../lib/middleware/serveResources", {
Ah, sorry, I must have missed that

2024-01-26 10:59 UTC, d3xter666 commented on test/lib/server/middleware/serveResources.js
> +	t.is(content, expected);
I got confused by `expected` that it's an object. Sorry

2024-01-26 11:01 UTC, d3xter666 reviewed
LGTM

2024-01-31 15:07 UTC, matz3 commented on lib/middleware/serveResources.js
> +				await manifestEnricher({
The processor modifies the resource (via setString), which can cause some inconsistent behaviour during development regarding caching, so we might need to disable etag caching for manifest.json. I need to check this again to understand when it exactly happens..

2024-01-31 16:26 UTC, RandomByte requested changes

2024-03-26 10:55 UTC, flovogt commented on lib/middleware/serveResources.js
> +const rManifest = /manifest.json$/i;
Done

2024-04-29 14:51 UTC, matz3 reviewed
LGTM

2024-07-09 15:07 UTC, RandomByte approved these changes

2024-07-12 13:59 UTC, merged